
name: ci
on:
  push:
    tags: [ "v*" ]
    branches: [ main ]
  pull_request:
    branches: [ "*" ]
jobs:
  build:
    name: ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          stable: true
          go-version: 1.22.5
      - uses: actions/checkout@v3
      - run: mkdir -p ui/dist && touch ui/dist/empty
      - name: run go mod
        run: go mod tidy && go build
